# Generated by Django 6.0 on 2025-12-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, help_text='Дата, к которой нужно выполнить задачу', null=True, verbose_name='Срок выполнения'),
        ),
    ]
