# Generated by Django 6.0 on 2025-12-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_task_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя отправителя', max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(help_text='Email адрес отправителя', max_length=254, verbose_name='Email')),
                ('message', models.TextField(help_text='Текст сообщения', verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время отправки сообщения', verbose_name='Дата отправки')),
                ('is_read', models.BooleanField(default=False, help_text='Отметьте, если сообщение прочитано', verbose_name='Прочитано')),
            ],
            options={
                'verbose_name': 'Сообщение обратной связи',
                'verbose_name_plural': 'Сообщения обратной связи',
                'ordering': ['-created_at'],
            },
        ),
    ]
